=== AlexZuniga92x/lhcb-software/LbScripts/LbConfiguration/data/LHCbMainConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="mainConfiguration" type="MainConfigurationType" />

	<xs:complexType name="MainConfigurationType">
		<xs:sequence>
			<xs:element name="distributionUrl" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="pythonVersion" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="CMTVersion" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="tbroadcastVersion" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="doxygenVersion" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="externalProjects" type="ProjectListType" />
			<xs:element name="LCGProjects" type="ProjectListType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ProjectListType">
		<xs:sequence>
			<xs:element name="project" type="xs:string" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== AlexZuniga92x/lhcb-software/LbScripts/LbConfiguration/tests/ExampleLHCbMainConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<mainConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../data/LHCbMainConfig.xsd">
	<distributionUrl>http://cern.ch/lhcbproject/dist</distributionUrl>
	<pythonVersion>2.5</pythonVersion>
	<CMTVersion>v1r20p20090520</CMTVersion>
	<tbroadcastVersion>v2.0.5</tbroadcastVersion>
	<doxygenVersion>1.7.2</doxygenVersion>
	<externalProjects>
		<project>LCGMT</project>
		<project>GENSER</project>
		<project>OpenScientist</project>
	</externalProjects>
	<LCGProjects>
		<project>LCGMT</project>
		<project>SEAL</project>
		<project>POOL</project>
		<project>GENSER</project>
		<project>COOL</project>
		<project>GDML</project>
		<project>CORAL</project>
		<project>RELAX</project>
	</LCGProjects>
</mainConfiguration>
