=== AlexZuniga92x/lhcb-software/LHCb/GaudiObjDesc/xml_files/gdd.dtd
<?xml encoding="ISO-8859-1"?>
<!ELEMENT gdd (import*, (package+ | class))>
<!ATTLIST gdd
	version CDATA "1.0"
>
<!ELEMENT import EMPTY>
<!ATTLIST import
	name CDATA #REQUIRED
	std (TRUE | FALSE) "FALSE"
	soft (TRUE | FALSE) "FALSE"
>
<!ELEMENT package (import*, class*)>
<!ATTLIST package
	name CDATA #REQUIRED
>
<!ELEMENT class (base*, import*, method*, attribute*, relation*)>
<!ATTLIST class
	name CDATA #REQUIRED
	author CDATA #REQUIRED
	desc CDATA #IMPLIED
	filename CDATA #IMPLIED
	id CDATA #IMPLIED
	templateVector (TRUE | FALSE) "TRUE"
	templateList (TRUE | FALSE) "TRUE"
>
<!ELEMENT base EMPTY>
<!ATTLIST base
	name CDATA #REQUIRED
	virtual (TRUE | FALSE) "TRUE"
	access (PUBLIC | PROTECTED | PRIVATE) "PUBLIC"
>
<!ELEMENT method (arg?, return, code?)>
<!ATTLIST method
	name CDATA #REQUIRED
	desc CDATA #IMPLIED
	access (PUBLIC | PROTECTED | PRIVATE) "PUBLIC"
	const (TRUE | FALSE) "FALSE"
	virtual (TRUE | FALSE) "FALSE"
	static (TRUE | FALSE) "FALSE"
	inline (TRUE | FALSE) "FALSE"
>
<!ELEMENT arg EMPTY>
<!ATTLIST arg
	type CDATA #REQUIRED
	const (TRUE | FALSE) "FALSE"
	inout (INPUT | OUTPUT | BOTH) "BOTH"
>
<!ELEMENT return EMPTY>
<!ATTLIST return
	type CDATA #REQUIRED
	const (TRUE | FALSE) "FALSE"
>
<!ELEMENT code (#PCDATA)>
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
	type CDATA #REQUIRED
	name CDATA #REQUIRED
	desc CDATA #IMPLIED
	access (PUBLIC | PROTECTED | PRIVATE) "PRIVATE"
	set_meth (TRUE | FALSE) "TRUE"
	get_meth (TRUE | FALSE) "TRUE"
>
<!ELEMENT relation EMPTY>
<!ATTLIST relation
	type CDATA #REQUIRED
	name CDATA #REQUIRED
	desc CDATA #IMPLIED
	access (PUBLIC | PROTECTED | PRIVATE) "PRIVATE"
	ratio (1-1 | 1-M | M-N) "1-1"
	set_meth (TRUE | FALSE) "TRUE"
	get_meth (TRUE | FALSE) "TRUE"
	add_meth (TRUE | FALSE) "TRUE"
	rem_meth (TRUE | FALSE) "TRUE"
	clr_meth (TRUE | FALSE) "TRUE"
>

=== AlexZuniga92x/lhcb-software/Rec/Tr/TrackFitEvent/xml/VLLiteRMeasurement.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'>
<gdd>
  <package name = 'TrackFitEvent'>
    <class name = 'VLLiteRMeasurement'
           desc = 'Measurement made from an R-type VLLiteCluster.'
           author = ''
           defaultconstructor = 'FALSE'
           serializers = 'FALSE'>
      <base name = 'LHCb::VLLiteMeasurement'/>
      <import name = 'Event/VLLiteMeasurement' />
      <import name = 'TrackInterfaces/IVLClusterPosition'/>
      <import name = 'StateVector' soft = 'FORWARDONLY'/>
      <import name = 'Event/VLLiteCluster'/>
      <import name = 'DeVL' namespace = '::' soft = 'FORWARDONLY'/>
      <import name = 'DeVLRSensor' namespace = '::' soft = 'FORWARDONLY'/>

      <constructor desc = 'Constructor from VLLiteCluster and refVector'>
        <arg type = 'LHCb::VLLiteCluster' name = 'cluster' const = 'TRUE'/>
        <arg type = 'DeVL' name = 'det' const = 'TRUE' />
        <arg type = 'IVLClusterPosition' name = 'clusPosTool' const = 'TRUE'/>
        <arg type = 'LHCb::StateVector' name = 'refVector' const = 'TRUE'/>
      </constructor>

      <constructor desc = 'Constructor from VLLiteCluster without refVector'>
        <arg type = 'LHCb::VLLiteCluster' name = 'cluster' const = 'TRUE'/>
        <arg type = 'DeVL' name = 'det' const = 'TRUE'/>
        <arg type = 'IVLClusterPosition' name = 'clusPosTool' const = 'TRUE'/>
      </constructor>

      <method name = 'init'
              desc = 'Initialize the data members'
              access = 'PUBLIC'>
        <arg type = 'DeVL' name = 'det' const = 'TRUE'/>
        <arg type = 'IVLClusterPosition::toolInfo' name = 'clusinfo' const='TRUE'/>
      </method>

      <method type = 'LHCb::VLLiteRMeasurement*'
              name = 'clone'
              desc = 'Clone the VLLiteRMeasurement'
              const = 'TRUE'>
        <code>
  return new LHCb::VLLiteRMeasurement(*this);
        </code>
      </method>

      <method type = 'const DeVLRSensor&amp;'
              name = 'sensor'
              desc = 'Retrieve the sensor of the measurement'
              const = 'TRUE'>
      </method>

    </class>
  </package>
</gdd>

=== AlexZuniga92x/lhcb-software/LHCb/Event/VeloLiteEvent/xml/MCVeloLiteDigit.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE gdd SYSTEM "gdd.dtd" >
<gdd>
  <package name="MCEvent">
  <class name="MCVeloLiteDigit" 
         id="4301"
         author="H. Schindler" 
         desc="Output of front-end chip for a single output channel."
         location="MC/VeloLite/Digits">
    <template name="KeyedObjectDict" t1="LHCb::VeloLiteChannelID"/>
    <location name="MCVeloLiteDigitLocation"   place="MC/VeloLite/Digits"/>
    <location name="MCPuVeloLiteDigitLocation" place="MC/VeloLite/PuDigits"/>
    <base name="KeyedObject&lt;LHCb::VeloLiteChannelID&gt;"/>
    &KeyedContainer;
    <import name="GaudiKernel/SmartRef"/>
    <import name="Kernel/VeloLiteChannelID"/>
    <import name="Event/MCHit"/>
    <import name="vector" std="TRUE"/>

    <constructor desc="Constructor with key" 
                 initList="KeyedObject&lt;LHCb::VeloLiteChannelID&gt;(key),
                           m_signal(0.0),
                           m_pedestal(0.0),
                           m_noise(0.0),
                           m_cmnoise(0.0)">
      <arg type="LHCb::VeloLiteChannelID" name="key" const="TRUE"/>
      <code/>                 
    </constructor> 

    <method name="channelID" 
            type="LHCb::VeloLiteChannelID" 
            desc="Combined sensor and strip number ID" 
            const="TRUE">
      <code>
        return key();
      </code>
    </method>

    <method name="sensor" 
            type="long" 
            desc="Sensor number" 
            const="TRUE">
      <code>
        return key().sensor();
      </code>
    </method>

    <method name="strip" 
            type="long" 
            desc="Strip number" 
            const="TRUE">
      <code>
        return key().strip();
      </code>
    </method>

    <attribute name="signal" 
               type="double" 
               desc="signal in units of electrons"/>
    <attribute name="pedestal" 
               type="double" 
               desc="pedestal in units of electrons"/>
    <attribute name="noise" 
               type="double" 
               desc="noise in units of electrons"/>
    <attribute name="cmnoise" 
               type="double" 
               desc="common mode noise in units of electrons"/>
    <attribute name="adc"
               type="int"
               desc="ADC value"/>

    <relation name="MCHits" 
              type="LHCb::MCHit" 
              desc="references to Monte Carlo hits contributing to this channel" 
              multiplicity="m"/>
 
    <attribute name="MCHitsCharge" 
               type="std::vector&lt;double&gt;" 
               desc="charge of Monte Carlo hit contributed to this channel"/>

    <method name="addToMCHits" 
            type="void" 
            argList="SmartRef&lt;LHCb::MCHit&gt; hit, double chg" 
            desc="Add MC hit and its deposited charge">
      <code>
        m_MCHits.push_back(hit);
        m_MCHitsCharge.push_back(chg);
      </code>
    </method>        

    <method name="mcHit" 
            type="SmartRef&lt;LHCb::MCHit&gt;" 
            argList="long num" 
            desc="retrieve MCHit reference" 
            const="TRUE">
      <code>
       return m_MCHits[num];
      </code>
    </method>

    <method name="mcHitCharge" 
            type="double" 
            argList="long num" 
            desc="retrieve deposited charge of MCHit" 
            const="TRUE">
      <code>
        return m_MCHitsCharge[num];
      </code>
    </method>

    <method name="setMCHitCharge" 
            type="void" 
            argList="long num, double chg" 
            desc="set deposited charge of MCHit">
      <code>
        m_MCHitsCharge[num] = chg;
      </code>
    </method>

    <method name="numberOfMCHits" 
            type="long" 
            desc="number of strips in cluster" 
            const="TRUE">
      <code>
        return mcHits().size();
      </code>
    </method>

    <method name="charge" 
            type="double" 
            desc="access total charge - in electrons"
            const="TRUE">
      <code>
        return signal() + noise() + pedestal() + cmnoise();
      </code>
    </method> 

  </class>
  </package>
</gdd>

=== AlexZuniga92x/lhcb-software/LHCb/Event/TrackEvent/xml/Trajectory.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'>
<gdd>
  <package name='TrackEvent'>

<!-- ==================== Trajectory class definition ==================== -->

    <class
      name             = 'Trajectory'
      author           = 'Edwin Bos, Jeroen van Tilburg, Eduardo Rodrigues'
      desc             = 'Trajectory is the base class for the trajectory classes.'
      id               = '10030'
      location         = 'Rec/Track/Traj'
      serializers      = 'FALSE'>

      <import name='GaudiKernel/KeyedContainer' />
      <import name='CLHEP/Geometry/Point3D' />
      <import name='CLHEP/Geometry/Vector3D' />
      <import name='CLHEP/Matrix/Matrix' />

      <constructor
        desc = 'Default constructor' />

      <method
        name    = 'expansion'
        desc    = 'Create a parabolic approximation to the Trajectory'
        const   = 'TRUE'
        virtual = 'TRUE'>
        <arg type = 'double' name='arclength' inout='BOTH' />
        <arg type = 'HepPoint3D' name='p' />
        <arg type = 'HepVector3D' name='dp' />
        <arg type = 'HepVector3D' name='ddp' />
      </method>

      <method
        type    = 'const HepMatrix'
        name    = 'derivative'
        desc    = 'Retrieve the derivative of the parabolic approximation to the Trajectory with respect to the State parameters'
        const   = 'TRUE'
        virtual = 'TRUE'>
        <arg type = 'const double' name='arclength' />
      </method>

    </class>

  </package>
</gdd>
