=== AlexZuniga92x/lhcb-software/LHCb/GaudiObjDesc/xml_files/gdd.dtd
<?xml encoding="ISO-8859-1"?>
<!ELEMENT gdd (import*, (package+ | class))>
<!ATTLIST gdd
	version CDATA "1.0"
>
<!ELEMENT import EMPTY>
<!ATTLIST import
	name CDATA #REQUIRED
	std (TRUE | FALSE) "FALSE"
	soft (TRUE | FALSE) "FALSE"
>
<!ELEMENT package (import*, class*)>
<!ATTLIST package
	name CDATA #REQUIRED
>
<!ELEMENT class (base*, import*, method*, attribute*, relation*)>
<!ATTLIST class
	name CDATA #REQUIRED
	author CDATA #REQUIRED
	desc CDATA #IMPLIED
	filename CDATA #IMPLIED
	id CDATA #IMPLIED
	templateVector (TRUE | FALSE) "TRUE"
	templateList (TRUE | FALSE) "TRUE"
>
<!ELEMENT base EMPTY>
<!ATTLIST base
	name CDATA #REQUIRED
	virtual (TRUE | FALSE) "TRUE"
	access (PUBLIC | PROTECTED | PRIVATE) "PUBLIC"
>
<!ELEMENT method (arg?, return, code?)>
<!ATTLIST method
	name CDATA #REQUIRED
	desc CDATA #IMPLIED
	access (PUBLIC | PROTECTED | PRIVATE) "PUBLIC"
	const (TRUE | FALSE) "FALSE"
	virtual (TRUE | FALSE) "FALSE"
	static (TRUE | FALSE) "FALSE"
	inline (TRUE | FALSE) "FALSE"
>
<!ELEMENT arg EMPTY>
<!ATTLIST arg
	type CDATA #REQUIRED
	const (TRUE | FALSE) "FALSE"
	inout (INPUT | OUTPUT | BOTH) "BOTH"
>
<!ELEMENT return EMPTY>
<!ATTLIST return
	type CDATA #REQUIRED
	const (TRUE | FALSE) "FALSE"
>
<!ELEMENT code (#PCDATA)>
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
	type CDATA #REQUIRED
	name CDATA #REQUIRED
	desc CDATA #IMPLIED
	access (PUBLIC | PROTECTED | PRIVATE) "PRIVATE"
	set_meth (TRUE | FALSE) "TRUE"
	get_meth (TRUE | FALSE) "TRUE"
>
<!ELEMENT relation EMPTY>
<!ATTLIST relation
	type CDATA #REQUIRED
	name CDATA #REQUIRED
	desc CDATA #IMPLIED
	access (PUBLIC | PROTECTED | PRIVATE) "PRIVATE"
	ratio (1-1 | 1-M | M-N) "1-1"
	set_meth (TRUE | FALSE) "TRUE"
	get_meth (TRUE | FALSE) "TRUE"
	add_meth (TRUE | FALSE) "TRUE"
	rem_meth (TRUE | FALSE) "TRUE"
	clr_meth (TRUE | FALSE) "TRUE"
>

=== AlexZuniga92x/lhcb-software/LHCb/Event/MCEvent/xml/MCParticle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd" >
<gdd>
  <package name='Event'>
<!-- ****************************************************************
     * MCParticle                                                   *
     ****************************************************************-->

     <class
      author="Gloria Corti, revised by P. Koppenburg"
      desc="The Monte Carlo particle kinematics information"
      id="210"
      name="MCParticle"
      location="MC/Particles"
     >
       &KeyedObject;
       <import name="Event/LHCbTypedefs"/>
       <import name="CLHEP/Units/PhysicalConstants"/>
       <import name="Kernel/ParticleID"/>
       <import name="MathCore/LorentzVectorfwd"/>
       <import name="MathCore/LorentzVector"/>
       <base name="KeyedObject&lt;int&gt;"/>
       <attribute
        desc="4-momentum-vector"
        name="momentum"
        type="LHCb::Momentum"
        init="0.0, 0.0, 0.0, -1*GeV" 
       />
       <attribute
        desc="Particle ID"
        name="particleID"
        type="ParticleID"
        init="0"
       />
       <method
        const="TRUE"
        desc="Describe if a particle has oscillated"
        name="hasOscillated"
        type="bool"
       >
         <code>  ; 
  for ( SmartRefVector &lt; MCVertex &gt;::const_iterator v = this->endVertices().begin() ;
         v != this->endVertices().end() ; ++v){
    if ( (*v)->type() == MCVertex::OscillatedAndDecay ) return true ;
  }
  return false ;
         </code>
       </method>
       <method
        const="TRUE"
        desc="Retrieve virtual mass, i.e. sqrt(E^2-P^2)"
        name="virtualMass"
        type="double"
       >
         <code>  return m_momentum.M(); </code>
       </method>
       <method
        const="TRUE"
        desc="Short-cut to pt value"
        name="pt"
        type="double"
       >
         <code> return m_momentum.Pt(); </code>
       </method>
       <method
        name="p"
        const="TRUE"
        desc="short cut for |P|" 
        type="double"
       > 
         <code> return m_momentum.R(); </code>
       </method>
       <method
        const="TRUE"
        desc="Pointer to parent particle"
        name="mother"
        type="const MCParticle*"
       >
         <code>
  return ( originVertex() ? originVertex()->mother() :0 ) ;
         </code>
       </method>
       <method
        const="TRUE"
        desc="Beta of the particle - no method in XYZTVector ?"
        name="beta"
        type="double"
       >
         <code>
  return ( m_momentum.E() > 0. ? m_momentum.R()/m_momentum.E() : 1.) ;
         </code>
       </method>
       <method
        const="TRUE"
        desc="Gamma of the particle"
        name="gamma"
        type="double"
       >
         <code>
  return ( m_momentum.M() > 0. ? m_momentum.E()/m_momentum.M() : -999.) ;
         </code>
       </method>
       <method
        const="TRUE"
        desc="Pseudorapidity of the particle"
        name="pseudoRapidity"
        type="double"
       >
         <code>
  return  m_momentum.eta() ;
         </code>
       </method>
       <relation
        desc="Pointer to origin vertex"
        name="originVertex"
        type="MCVertex"
       />
       <relation
        desc="Vector of pointers to decay vertices"
        multiplicity="M"
        name="endVertices"
        type="MCVertex"
       />
       <method
        const="TRUE"
        desc="Get primary vertex up the decay tree"
        name="primaryVertex"
        type="const MCVertex*"
       >
         <code> 
  return ( originVertex() ? originVertex()->primaryVertex() : 0 ) ;
         </code>
       </method>
     </class>
  </package>
</gdd>

=== AlexZuniga92x/lhcb-software/LHCb/Kernel/LHCbKernel/xml/LHCbID.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd">
<gdd>
  <package name="LHCbKernel">

    <class
       name   = "LHCbID"
       desc   = "LHCb wide channel identifier"
       author = "Marco Cattaneo" >

       <import name="Kernel/VeloChannelID"/>
       <import name="Kernel/ITChannelID"/>
       <import name="Kernel/OTChannelID"/>
       <import name="Kernel/RichSmartID"/>
       <import name="Kernel/CaloCellID"/>

       &StlVector;

       <enum
          desc  = "types of sub-detector channel ID"
          name  = "channelIDType"
          value = "veloType=1, stType, otType, richType, caloType, muonType"
       />

       <attribute
          desc = "the internal representation" name="lhcbID"
          type = "bitfield"
          setMeth = "FALSE" >
            <bitfield desc="the detector specific bits" length="28" name="specific" />
            <bitfield desc="the LHCb generic bits"      length="4"  name="common"   />
       </attribute>

       <method type='bool' name='operator==' argList='const LHCbID chanID' const='TRUE' desc='comparison equality'>
         <code> return (this->lhcbID() == chanID.lhcbID()); </code>
       </method>

       <constructor desc = "Constructor from VeloChannelID" initList = "m_lhcbID(0)" >
          <arg const="TRUE" name="chanID" type="VeloChannelID" />
          <code>
            setSpecific( chanID );
            setCommon( veloType );
          </code>
       </constructor>

       <method type="bool" name="isVelo" const='TRUE' desc="return true if this is a Velo identifier">
         <code>return (veloType == common()) ? true : false;</code>
       </method>

       <method type="VeloChannelID" name="veloID" const='TRUE' desc="return the VeloChannelID">
	 <code>return isVelo() ? specific() : 0x0;</code>
       </method>

       <constructor desc = "Constructor from ITChannelID" initList = "m_lhcbID(0)" >
          <arg const="TRUE" name="chanID" type="ITChannelID" />
          <code>
            setSpecific( ((chanID.uniqueWafer()-1)&gt;&gt;4) + (chanID.strip()-1) );
            setCommon( stType );
          </code>
       </constructor>

       <method type="bool" name="isST" const='TRUE' desc="return true if this is a Silicon Tracker identifier">
         <code>return (stType == common()) ? true : false;</code>
       </method>

       <method type="ITChannelID" name="stID" const='TRUE' desc="return the ITChannelID">
	 <code>return isST() ? ( ((specific()&amp;0xFFFF000)&lt;&lt;4)+(specific()&amp;0xFFF) ) : 0xF0000000;</code>
       </method>


       <constructor desc = "Constructor from OTChannelID" initList = "m_lhcbID(0)" >
          <arg const="TRUE" name="chanID" type="OTChannelID" />
          <code>
            setSpecific( chanID );
            setCommon( otType );
          </code>
       </constructor>

       <method type="bool" name="isOT" const='TRUE' desc="return true if this is a Outer Tracker identifier">
         <code>return (otType == common()) ? true : false;</code>
       </method>

       <method type="OTChannelID" name="otID" const='TRUE' desc="return the OTChannelID">
	 <code>return isOT() ? specific() : 0xF0000000;</code>
       </method>

       <constructor desc = "Constructor from RichSmartID" initList = "m_lhcbID(0)" >
          <arg const="TRUE" name="chanID" type="RichSmartID" />
          <code>
            unsigned int richData = chanID.dataBitsOnly();
            if( chanID.pixelDataAreValid() ) richData += 0x8000000;
            setSpecific( richData );
            setCommon( richType );
          </code>
       </constructor>

       <method type="bool" name="isRich" const='TRUE' desc="return true if this is a Rich identifier">
         <code>return (richType == common()) ? true : false;</code>
       </method>

       <method type="RichSmartID" name="richID" const='TRUE' desc="return the richSmartID">
	 <code>
	   unsigned int rID = 0;
	   if( isRich() ) {
	     rID = specific() &amp; 0x7000000;
	     if( specific() &amp;&amp; 0x8000000 ) rID += 0x7E000000;
           }
	   return rID;
         </code>
       </method>

       <constructor desc = "Constructor from CaloCellID" initList = "m_lhcbID(0)" >
          <arg const="TRUE" name="chanID" type="CaloCellID" />
          <code>
            setSpecific( chanID.ccid() );
            setCommon( caloType );
          </code>
       </constructor>

       <method type="bool" name="isCalo" const='TRUE' desc="return true if this is a Calo identifier">
         <code>return (caloType == common()) ? true : false;</code>
       </method>

       <method type="CaloCellID" name="caloID" const='TRUE' desc="return the CaloCellID">
	 <code>return isCalo() ? specific() : 0xF0000000;</code>
       </method>

    </class>
  </package>
</gdd>

=== AlexZuniga92x/lhcb-software/Alignment/Alignment/AlignEvent/xml/AlignSummaryData.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'>
<gdd>
  <package name='AlignEvent'>

<!-- ==================== class definition ==================== -->

    <class
      name        = 'AlignSummaryData'
      author      = ''
      desc        = ''
      id          = '10213'
      serializers = 'TRUE'
      allocator   = 'NO' >
      
      <base name="DataObject"/>
      &DataObject;
      
      <location name= "Default" place="FST/Alignment/SummaryData" />
      
      <import name='AlignKernel/AlEquations'/>

      <constructor
	desc     = "constructor from AlEquations object"
	argList  = "Al::Equations eq" 
	initList = "m_equations(eq)">
      </constructor>

      <constructor
	desc     = "constructor"
	argList  = "size_t size" 
	initList = "m_equations(size)">
      </constructor>

      <attribute 
	desc = "" 
	init = ""
	nonconstaccessor = "TRUE"
	name = "equations" 
	type = "Al::Equations"
        />  

      <method
	desc = ""
	name = "add"
	type = "void"
	argList = "AlignSummaryData rhs"
	const = "FALSE"
	/>  

      <method
	desc = "needs also function with capital because GaudyPthon.Parallel uses that"
	name = "Add"
	type = "void"
	const = "FALSE" > 
	<arg type = 'const AlignSummaryData' name='rhs' />
	<code>
     add(rhs) ;
      </code>
      </method>  
      
      <method
        name      = "fillStream"
        desc      = "printOut method to Gaudi message stream"
        type      = "std::ostream&amp;"
        virtual   = "TRUE"
        const     = "TRUE" >
        <arg name = "os" type = "std::ostream" inout = "BOTH"/>
      </method>

    </class>
    
  </package>
</gdd>

=== AlexZuniga92x/lhcb-software/LHCb/Event/VeloEvent/xml/VeloEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd">
<gdd>
  <package name="VeloEvent">

    <class name="MCVeloFE" 
           id="4002"
           author="Chris Parkes" 
           desc="This class represents the output of the front-end chip and
contains information about the simulation of the silicon and FE chip response 
stored for a single silicon/output channel. Constructed from MCHits 
(i.e. GEANT deposits), MCVeloFE of previous events (spill over), noise 
(above a threshold)"
           location="MC/Velo/FE">
      <template name="KeyedObjectDict" t1="VeloChannelID"/>
      <location name="PuVeto" place="MC/Velo/PuFE" />
      <base name="KeyedObject&lt;VeloChannelID&gt;"/>
      &KeyedContainer;
      <import name="Kernel/VeloChannelID"/>
      <import name="Kernel/SerializeStl"/>
      <constructor desc="Constructor with key" 
	initList="KeyedObject&lt;VeloChannelID&gt;(key),
	m_addedSignal(0.0),
	m_addedPedestal(0.0),
	m_addedNoise(0.0),
	m_addedCMNoise(0.0)" >
	<arg type="VeloChannelID" name="key" const="TRUE"/>
	<code/>                 
      </constructor> 
      <method name="channelID" type="VeloChannelID" desc="combined sensor and strip number ID" const="TRUE">
                   <code>return key();</code>
           </method>
           <method name="sensor" type="long" desc="Sensor Number" const="TRUE">
                  <code>return key().sensor();</code>
           </method>
           <method name="strip" type="long" desc="Strip Number" const="TRUE">
                 <code>return key().strip();</code>
           </method>
           <attribute name="addedSignal" type="double" desc="Added Signal in units of electrons"/>
           <attribute name="addedPedestal" type="double" desc="pedestal added in Si/FE chip simulation in units of electrons"/>
           <attribute name="addedNoise" type="double" desc="noise added in Si/FE chip simulation in units of electrons"/>
           <attribute name="addedCMNoise" type="double" desc="common mode noise added in Si/FE chip simulation in units of electrons"/>

           <relation name="MCHits" type="MCHit" desc="References to Monte Carlo hits contributing to this channel" multiplicity="m"/>

           <attribute name="MCHitsCharge" type="std::vector&lt;double&gt;" desc="Charge of Monte Carlo hit contributed to this channel" />
 
           <method name="addToMCHits" type="void" argList="SmartRef&lt;MCHit&gt; hit, double chg" desc="add MC hit and its deposited charge">
                 <code>m_MCHits.push_back(hit);
                       m_MCHitsCharge.push_back(chg);
                       return;
                 </code>
           </method>
           
          <method name="mcHit" type="SmartRef&lt;MCHit&gt;" argList="long num" desc="retrieve MCHit reference" const="TRUE">
           <code>return m_MCHits[num];</code>
           </method>

          <method name="mcHitCharge" type="double" argList="long num" desc="retrieve deposited charge of MCHit" const="TRUE">
           <code>return m_MCHitsCharge[num];</code>
           </method>

          <method name="setMCHitCharge" type="void" argList="long num, double chg" desc="set deposited charge of MCHit" >
           <code>m_MCHitsCharge[num]=chg;
                 return;
           </code>
           </method>

           <method name="NumberOfMCHits" type="long" desc="number of strips in cluster" const="TRUE">
                 <code>return mcHits().size();</code>
           </method>



           <method name="charge" type="double"  desc="Access total charge - in electrons" const="TRUE">
	           <code>return addedSignal()+addedNoise()+addedPedestal()+addedCMNoise();</code>
           </method> 

    </class>

<!-- VeloDigit -->
<!-- Simpler version of the VeloFullFPGADigit to store the FPGA objects -->
<!--           -->

 <class
  author="Tomasz Szumlak"
  desc="VeloDigit is a temporary object to store the ADC value obtained during
        one of the FPGA processing stages. The object is much more simple than
        VeloFullFPGADigit (has only one data member)"
  name="VeloDigit"
  location="Raw/Velo/Digits"
  >
   <base name="KeyedObject&lt;VeloChannelID&gt;"/>
   &KeyedContainer;

  <constructor
   desc="constructor with key"
   initList="KeyedObject&lt;VeloChannelID&gt;(key),
   m_ADCValue(0)"
  >
   <arg type="VeloChannelID" name="key" const="TRUE"/>
  </constructor>
 
  <method 
   name="channelID" 
   type="VeloChannelID" 
   desc="combined sensor and strip number ID" 
   const="TRUE"
  >          
   <code>
    return key();
   </code>
  </method>

  <method 
   name="sensor" 
   type="long" 
   desc="Sensor Number" 
   const="TRUE"
  >
   <code>
    return key().sensor();
   </code>
  </method>
   
  <method
   name="strip"
   type="long"
   desc=" "
   const="TRUE"
  >
   <code>
    return key().strip();
   </code>
  </method>

  <attribute
   name="ADCValue"
   type="short int"
   desc=" "
   setMeth="TRUE"
   getMeth="TRUE"
  />     
 </class>


    <class name="VeloCluster" 
     id="4004"
     author="Chris Parkes" 
     desc="A cluster as on the DAQ output, after the data processor and 
     without applying any additional processing. It contains no simulation info."
	   location="Raw/Velo/Clusters">
           <import name="Kernel/SerializeStl"/>
           <import name="Kernel/VeloChannelID"/>
	   <template name="KeyedObjectDict" t1="VeloChannelID"/>
           <base name="KeyedObject&lt;VeloChannelID&gt;"/>
           &KeyedContainer;
	   <constructor desc="Constructor with key" 
                        initList="KeyedObject&lt;VeloChannelID&gt;(key),
				  m_sensorID(0),
				  m_stripSignals()">
             <arg type="VeloChannelID" name="key" const="TRUE"/>
             <code/>  
           </constructor> 
           <attribute name="sensorID" type="VeloChannelID" desc="Sensor number stored as VeloChannelID"/>
           <attribute name="stripSignals" type="std::vector&lt;std::pair&lt;long,double&gt; &gt;" desc="strip numbers and their signals"/>
           
           <method name="size" type="long" desc="number of strips in cluster" const="TRUE">
                 <code>return stripSignals().size();</code>
           </method>
           <method name="adcValue" type="double" argList="long num" desc="adc value of strips in cluster" const="TRUE">
                 <code>return stripSignals()[num].second;</code>
           </method>
           <method name="sensor" type="long" desc="Sensor number" const="TRUE">
                 <code>return m_sensorID.sensor();</code>
           </method>
           <method name="strip" type="long" argList="long num" desc="strip number of strip in cluster" const="TRUE">
                 <code>return stripSignals()[num].first;</code>
           </method>
           <method name="setSensor" type="void" argList="long num" desc="Set the sensor number (overrides default)">           
                 <code>m_sensorID.setSensor(num);</code>
           </method>
           <method name="channelID" type="VeloChannelID" argList="long num" desc="combined sensor and strip number ID (key) of strip in cluster" const="TRUE">
                   <code>return VeloChannelID(m_sensorID.sensor(),strip(num),m_sensorID.type());</code>
           </method>

    </class>

  </package>

</gdd>

=== AlexZuniga92x/lhcb-software/Rec/Tr/TrackFitEvent/xml/MuonMeasurement.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'>
<gdd>
  <package name='TrackFitEvent'>

<!-- ================ MuonMeasurement class definition ================ -->

    <class
      name        = 'MuonMeasurement'
      author      = 'Jose Hernando, Miriam Gandelman, Erica Polycarpo'
      desc        = 'MuonMeasurement is a measurement made from a Muon Hit'
      serializers = 'FALSE'>

      <base name='LHCb::Measurement' />
      <import name='Event/Measurement' />
      <import name='Kernel/MuonTileID' />

      <constructor
        desc = 'Constructor from a Muon Hit'>
        <arg type='LHCb::LHCbID' name='lhcbID' const='TRUE' />
        <arg type='Gaudi::XYZPoint' name='position' const='TRUE' />
        <arg type='double' name='dx' />
        <arg type='double' name='dy' />
      </constructor>

     <constructor
        desc = 'Copy constructor'>
        <arg type='LHCb::MuonMeasurement' name='other' const='TRUE'/>
      </constructor>

      <attribute
        type = 'Gaudi::XYZPoint'
        name = 'position'
        desc = 'Position of the pad center'/>

      <attribute
        type = 'double'
        name = 'dx'
        desc = 'Half of pad length in x'/>

      <attribute
        type = 'double'
        name = 'dy'
        desc = 'Half of pad length in y'/>

     <attribute
        type    = 'std::auto_ptr &lt; LHCb::Trajectory &gt;'
        name    = 'trajectoryY'
        desc    = 'the trajectory representing the Y measurement (owner)'
        access  = 'PROTECTED'
        setMeth = 'FALSE' />
	
      <method
        type    = 'LHCb::MuonMeasurement*'
        name    = 'clone'
        desc    = 'Clone the MuonMeasurement'
        virtual = 'TRUE'
        const   = 'TRUE'>
        <code>
          return new LHCb::MuonMeasurement(*this);
        </code>
      </method>

      <method
        type    = 'double'
        name    = 'errX2'
        desc    = 'X error squared'
        const   = 'TRUE'>
        <code>
          return m_dx*m_dx/3.;
        </code>
      </method>

      <method
        type    = 'double'
        name    = 'errY2'
        desc    = 'Y error squared'
        const   = 'TRUE'>
        <code>
          return m_dy*m_dy/3.;
        </code>
      </method>

    </class>

  </package>
</gdd>

=== AlexZuniga92x/lhcb-software/Rec/Tr/TrackFitEvent/xml/TrajMeasurement.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'>
<gdd>
  <package name='TrackFitEvent'>

<!-- =============== TrajMeasurement class definition =============== -->

    <class
      name        = 'TrajMeasurement'
      author      = 'Jose Hernando, Eduardo Rodrigues'
      desc        = 'TrajMeasurement is a Measurement supplemented with a Trajectory.'
      serializers = 'FALSE'>

      <base name='LHCb::Measurement'/>

      <import name='Event/Measurement'/>
      <import name='Kernel/Trajectory.h'/>

      <constructor
        desc     = "Constructor from a Trajectory and an LHCbID"
        argList  = "LHCb::Trajectory* traj, const LHCb::LHCbID&amp; id"
        initList = "m_trajectory(traj)">
	<code>
  m_z = traj -> position( traj->range().first + 0.5 * traj->length() ).z();
  m_lhcbID = id;
	</code>
      </constructor>
      
      <destructor
	desc = "Destructor">
	<code>
    if ( m_trajectory != 0 ) delete m_trajectory;
	</code>
      </destructor>

      <constructor
        desc     = "Constructor from a Trajectory"
        argList  = "LHCb::Trajectory* traj"
        initList = "m_trajectory(traj)">
	<code>
  m_z = traj -> position( traj->range().first + 0.5 * traj->length() ).z();
	</code>
      </constructor>
      
      <destructor
	desc    = "Destructor"
	virtual = 'TRUE'>
	<code>
    if ( m_trajectory != 0 ) delete m_trajectory;
	</code>
      </destructor>

      <attribute
        type    = 'LHCb::Trajectory*'
        name    = 'trajectory'
        setMeth = 'FALSE'
        getMeth = 'FALSE'
        desc    = 'pointer to the Trajectory (owner)'
        access  = 'PROTECTED' />

      <method
        name    = 'update'
        desc    = 'Update the Measurement parameters'
        argList = 'const Gaudi::TrackVector refVector'
        virtual = 'TRUE'>
      </method>

      <method
        type    = 'LHCb::Trajectory &amp;'
        name    = 'trajectory'
        desc    = 'Retrieve the reference to the Trajectory'>
        <code>
  return *m_trajectory;
        </code>
      </method>

      <method
        type    = 'const LHCb::Trajectory &amp;'
        name    = 'trajectory'
        desc    = 'Retrieve const the reference to the Trajectory'
        const   = 'TRUE'>
        <code>
  return *m_trajectory;
        </code>
      </method>

      <method
        name    = 'setTrajectory'
        argList = 'LHCb::Trajectory traj'
        desc    = 'Update the trajectory'>
        <code>
  if ( m_trajectory != 0 ) delete m_trajectory;
  m_trajectory = traj.clone();
        </code>
      </method>

      <method
        type    = 'LHCb::TrajMeasurement*'
        name    = 'clone'
        desc    = 'Clone the TrajMeasurement'
        const   = 'TRUE'
	virtual = 'TRUE'>
        <code>
  LHCb::TrajMeasurement* me = new LHCb::TrajMeasurement( trajectory().clone() );
  return me;
        </code>
      </method>

    </class>
  </package>
</gdd>

=== AlexZuniga92x/lhcb-software/Rec/Tr/TrackFitEvent/xml/VeloLiteRMeasurement.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'>
<gdd>
  <package name='TrackFitEvent'>

<!-- =============== VeloLiteRMeasurement class definition =============== -->

    <class
      name        = 'VeloLiteRMeasurement'
      author      = 'David Hutchcroft'
      desc        = 'VeloLiteRMeasurement is a measurement made from a VeloLiteCluster.'
      defaultconstructor ='FALSE'
      serializers = 'FALSE'>

      <base name='LHCb::VeloLiteMeasurement' />

      <import name='Event/VeloLiteMeasurement' />
      <import name='TrackInterfaces/IVeloClusterPosition'/>
      <import name='StateVector' soft='FORWARDONLY'/>
      <import name='Event/VeloLiteCluster' />
      <import name='DeVelo' namespace='::' soft='FORWARDONLY'/>
      <import name='DeVeloRType' namespace='::' soft='FORWARDONLY'/>

      <constructor
        desc = 'Constructor from a VeloLiteCluster (R type) and refVector'>
        <arg type = 'LHCb::VeloLiteCluster' name = 'aCluster' const='TRUE' />
        <arg type = 'DeVelo' name = 'det' const='TRUE' />
        <arg type = 'IVeloClusterPosition' name = 'clusPosTool' const='TRUE' />
        <arg type = 'LHCb::StateVector' name='refVector' const='TRUE'/>
       </constructor>

      <constructor
        desc = 'Constructor from a VeloLiteCluster (R type) without refVector'>
        <arg type = 'LHCb::VeloLiteCluster' name = 'aCluster' const='TRUE' />
        <arg type = 'DeVelo' name = 'det' const='TRUE' />
        <arg type = 'IVeloClusterPosition' name = 'clusPosTool' const='TRUE' />
       </constructor>

      <method
        name   = 'init'
        desc   = 'Initialize the data members'
        access = 'PUBLIC'>
        <arg type = 'DeVelo' name = 'det' const='TRUE' />
        <arg type = 'IVeloClusterPosition::toolInfo' name = 'clusinfo'
	  const='TRUE' />
      </method>

      <method
        type    = 'LHCb::VeloLiteRMeasurement*'
        name    = 'clone'
        desc    = 'Clone the VeloLiteRMeasurement'
        const   = 'TRUE'>
        <code>
          return new LHCb::VeloLiteRMeasurement(*this);
        </code>
      </method>

     <method
       type = 'const DeVeloRType&amp;'
       name = 'sensor'
       desc = 'Retrieve const the sector of the measurement'
       const = 'TRUE'>
      </method>


    </class>

  </package>
</gdd>

=== AlexZuniga92x/lhcb-software/LHCb/Event/GenEvent/xml/HardInfo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd' >

<gdd>
  <package name="GenEvent">
    <class
      name   = "HardInfo"
      author = "G.Corti"
      desc   = "Holds parameters associated to hard scatter: Mandelstam variables and Bjorken-x for both incoming partons"
      location = "Gen/HardProcesses"
      id     = "203"
    > 
      &KeyedObject;
      <base name = "KeyedObject&lt;int&gt;"/>
      <attribute
       desc  = "Mandelstam s hat"
       name  = "sHat"
       type  = "double"
       init  = "0.0"
      />
      <attribute
       desc  = "Mandelstam t hat"
       name  = "tHat"
       type  = "double"
       init  = "0.0"
      />
      <attribute
       desc  = "Mandelstam u hat"
       name  = "uHat"
       type  = "double"
       init  = "0.0"
      />
      <attribute
       desc  = "Mandelstam pt hat"
       name  = "ptHat"
       type  = "double"
       init  = "0.0"
      />
      <attribute
       desc  = "Bjorken x1"
       name  = "x1Bjorken"
       type  = "double"
       init  = "0.0"
      />
      <attribute
       desc  = "Bjorken x2"
       name  = "x2Bjorken"
       type  = "double"
       init  = "0.0"
      />
      <relation
       desc  = "Reference to HepMC Event of this collision"
       name  = "event"
       type  = "HepMCEvent"
      />

    </class>    

  </package>
</gdd>
